# Setup
title: Marcos Ramon
tagline: Textos e podcasts sobre filosofia, arte, tecnologia
url: https://marcosramon.net
paginate: 5
baseurl: "http://marcosramon.net"
permalink: /:categories/:title

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0
ga_analytics: UA-25904919-5

# Specify the author for blog posts
author:
  name: Marcos Ramon
  url: https://twitter.com/mrtollens
  email: contato@marcosramon.net

# Custom vars
version: 3.0.0
